name: Java CI with Maven Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 8
            maven-args: "-P jacoco coveralls:report -D repoToken=$COVERALLS_REPO_TOKEN"
          - java: 11

    name: Build with Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' 
        java-version: ${{ matrix.java }}

    - name: Build with Maven
      run: >
        mvn -f Continus-Integration/pom.xml
        clean verify ${{ matrix.maven-args }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN}}

    - name: Generate JUnit Report
      run: >
        mvn -f Continus-Integration/pom.xml
        surefire-report:report-only site:site -DgenerateReports=false
      if: ${{ always() }}

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: surefire-report-jdk-${{ matrix.java }}
        path: '**/target/site'
