name: Java CI with Maven Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: Continus-Integration
    strategy:
      matrix:
        include:
          - java: 8
            maven-args: >
              -P coveralls
              -D repoToken=$COVERALLS_REPO_TOKEN
              -D pullRequest=${{github.event.pull_request.number}}
          - java: 11

    name: Build with Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' 
        java-version: ${{ matrix.java }}
        cached: 'maven'

    - name: Build with Maven
      run: >
        mvn verify ${{ matrix.maven-args }}
      working-directory: ${{ env.workdir }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN}}

    - name: Generate JUnit Report
      run: >
        mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}

    - name: Archive JUnit Report
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: surefire-report-jdk-${{ matrix.java }}
        path: '**/target/site'
