name: Java CI with Maven on differnt OS

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      workdir: Continus-Integration
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    name: Build with Java 8 on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cached: 'maven"

    - name: Build with Maven
      run: mvn verify
      working-directory: ${{ env.workdir }}
